# Site settings
title: K.C. Jones-Evans
description: Hello World!
cover: assets/images/intro-bg.jpg
logo: /assets/images/cream_logo_transparent.png
favicon: assets/images/favicon.ico
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://kcjonesevans.com/" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
facebook: kcjonesevans
twitter: kcjonesevans
github:  kcjonesevans

#Additional Pages
about: about
resume: resume
contact: contact


permalink: /:title


# Google Analytics
analytics_id: "UA-74637360-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: samanyougarg #github username
repo: hanuman #github repository
branch: master #branch
relative_source: ../kcjonesevans/ #source directory
destination: ../kcjonesevans-pages/ #destination directory
production_url:  https://kcjonesevans.com/
source_url:  https://github.com/kcjonesevans/kcjonesevans.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - _posts/archieve/*

  